name: Build OpenFuelCell2 in OpenFOAM Container

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container-image:
          - ghcr.io/nonannet/nonannet/openfoam_ci_docker_images_com_gcc:2306
          - ghcr.io/nonannet/nonannet/openfoam_ci_docker_images_com_clang:_2306
          - ghcr.io/nonannet/nonannet/openfoam_ci_docker_images_org_gcc:13

    container:
      image: ${{ matrix.container-image }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          WM_PROJECT_DIR=$(ls -d /home/openfoam/OpenFOAM-* | sort -V | tail -1)
          echo "WM_PROJECT_DIR=$WM_PROJECT_DIR" >> $GITHUB_ENV

      - name: Build
        run: |
          set +e
          source $WM_PROJECT_DIR/etc/bashrc
          set -e
          cd src
          ./Allwmake

      - name: Test
        run: |
          set +e
          source $WM_PROJECT_DIR/etc/bashrc
          set -e
          cd run/SOFC
          make mesh
          make srun
