name: Build OpenFuelCell2 in OpenFOAM Container

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/nonannet/nonannet/openfoam_ci_docker_images_com_2306:latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          WM_PROJECT_DIR=/home/openfoam/OpenFOAM-2306
          echo "WM_PROJECT_DIR=$WM_PROJECT_DIR" >> $GITHUB_ENV

      - name: Build
        run: |
          set +e
          source $WM_PROJECT_DIR/etc/bashrc
          set -e
          cd src
          ./Allwmake

      - name: Test
        run: |
          set +e
          source $WM_PROJECT_DIR/etc/bashrc
          set -e
          cd run/SOFC
          make mesh
          make srun
